name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install -g yarn
        
      - name: Check lint
        run: yarn check:lint
        
      - name: Check prettier
        run: yarn check:prettier
      
      - name: Build
        run: yarn build