name: build gatsby
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GA_TRACKING_ID: ${{ vars.GA_TRACKING_ID }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Checkout submodules
        run: git submodule update --init --recursive --remote

      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          deploy-branch: gh-pages
          skip-publish: false
